### ISSUE TITLE
Hi Can i get some help with installing the project as i am having issues

### ISSUE THREAD

**Issue by BlueDefenders** [aaditya-patil-0018/Job-Applier-Bot#1]

**Comment by BlueDefenders** [comment]
Traceback (most recent call last):
  File "/Users/Jamshaid/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/Users/Jamshaid/opt/anaconda3/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/Users/Jamshaid/opt/anaconda3/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 14, in <module>
    driver = webdriver.Firefox()	
  File "/Users/Jamshaid/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/Users/Jamshaid/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by aaditya-patil-0018** [comment]
First of all you need Firefox Browser to be installed in your machine. Secondly you need to download its driver, you can download it from [here](https://github.com/mozilla/geckodriver/releases). If you don't want to download Firefox and open in chrome you need to download chrome driver and instead of Firefox driver's path you need to specify chrome driver's path in the code, you can get chrome driver from [here](https://chromedriver.chromium.org/downloads)..
